import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import SidebarClientGate from "@/components/SidebarClientGate";
import MobileMenu from "@/components/MobileMenu";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased bg-background text-foreground`}>
        <div className="min-h-dvh grid grid-cols-1 md:grid-cols-[auto_1fr]">
          <SidebarClientGate />
          <div>
            <MobileMenu />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
